version: '3.1'

services:
  database:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=schedule_boot
    volumes:
      - pg:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  spring-boot-app:
    container_name: schedule-app
    image: schedule-app-image
    build: ./
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/schedule_boot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - database
    ports:
      - "8082:8080"
      - "5005:5005"
    volumes:
      - maven:/root/.m2
volumes:
  pg:
  maven: