spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule_boot
    username: postgres
    password: root
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: debug
    